---
functional:
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре

non-functional:
- Сайт должен быть безопасным и защищать данные пользователя
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Сайт должен иметь мобильную версию
- Сайт должен быть доступен на различных устройствах

implicit:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
